version: '3.8'

services:
  week6task:
    image: week6task
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 19000:19000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
