version: '3.8'

services:
  week6task:
    image: week6task
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 19000:19000
